var fs = require('fs');
var path = require('path');
var mailer = require('../components/mailer');
var moment = require('moment');

module.exports.saveChartImage = function(req, res) {
    var base64Data = req.body.stream.replace(/^data:image\/png;base64,/, "");
    var file = '/share/chart-' + new Date().getTime() + '.png';
    fs.writeFile(path.resolve(__dirname + '/../../public' + file), base64Data, 'base64', err => {
        if (err)
            return res.status(502).send('Server issue: ' + err.message);

        res.status(200).json({
          filename: file
        });
    });
};

module.exports.sendEmail = function(req, res) {
    var imgSize = req.body.setSize ? ' width="400" ' : '';
    var mailBody = '<p>Hello,</p>' +
        '<p>' + req.body.user + ' shared with you the ' + req.body.subject + ' generated by TrenData ' + req.body.date + '</p>' +
        '<p style="text-align: center">' +
        (req.body.comment ? '<i style="color: #e68a8a">"' + req.body.comment.replace(/\n/g, '<br>') + '"</i>' : '') +
        '<br><img' + imgSize + ' src="' + req.body.image + '"></p>' +
        '<p>Sincerely!</p>'+
        '<p>TrenData Administration</p>';

    _.each(req.body.emails, email => {
        mailer({
            to: email.trim(),
            subject: 'TrenData - ' + req.body.subject,
            html: mailBody,
        });
    });

  res.status(200).send('success');
};